/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package my.study.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum WorkDomain {
  IT, ECONOMY, CULTURE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WorkDomain\",\"namespace\":\"my.study.model\",\"symbols\":[\"IT\",\"ECONOMY\",\"CULTURE\"],\"default\":\"CULTURE\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
